### PR TITLE
Remove tbdex related features

### PR DESCRIPTION
**Pull request by phoebe-lew**
Moved to `tbdex` repo: https://github.com/TBD54566975/tbdex/pull/188

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]

**Comment by decentralgabe** [comment]
eventually I think we should add back "web5 message formats" which are used by tbdex. if you agree (@mistermoe @phoebe-lew) I can open an issue

**Comment by phoebe-lew** [comment]
@decentralgabe what's an example of a web5 message format?

**Comment by decentralgabe** [comment]
tbdex message formats that we define here as a generic authenticated message payload

**Comment by phoebe-lew** [comment]
@decentralgabe i'm still confused how that's a web5 message and not just a tbdex message...feel free to chuck up a PR if it's easier to explain via example!

**Review by mistermoe — APPROVED** [review]
🏅

**Comment by decentralgabe** [comment]
@phoebe-lew its the same thing I'm proposing a rename

**Pull request merged**
